### ISSUE TITLE
the url of dataset cannot be accessible

### ISSUE THREAD

**Issue by r666ay** [HuanLinMaster/Genshin-VitsWeb#5]
数据集的下载链接https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth，这个目前没办法注册账户并下载，请问有其他的下载数据集的方式吗？

**Comment by iplanc** [comment]
https://github.com/w4123/GenshinVoice


> 数据集的下载链接[https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth，这个目前没办法注册账户并下载，请问有其他的下载数据集的方式吗？](https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%89%8D%E6%B2%A1%E5%8A%9E%E6%B3%95%E6%B3%A8%E5%86%8C%E8%B4%A6%E6%88%B7%E5%B9%B6%E4%B8%8B%E8%BD%BD%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%9C%89%E5%85%B6%E4%BB%96%E7%9A%84%E4%B8%8B%E8%BD%BD%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E6%96%B9%E5%BC%8F%E5%90%97%EF%BC%9F)

**Comment by bakasine** [comment]
> https://github.com/w4123/GenshinVoice
> 
> > 数据集的下载链接[https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth，这个目前没办法注册账户并下载，请问有其他的下载数据集的方式吗？](https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%89%8D%E6%B2%A1%E5%8A%9E%E6%B3%95%E6%B3%A8%E5%86%8C%E8%B4%A6%E6%88%B7%E5%B9%B6%E4%B8%8B%E8%BD%BD%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%9C%89%E5%85%B6%E4%BB%96%E7%9A%84%E4%B8%8B%E8%BD%BD%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E6%96%B9%E5%BC%8F%E5%90%97%EF%BC%9F)

这个项目只提供原神提取的音频素材 没有数据集啊

**Comment by HuanLinOTO** [comment]
> > https://github.com/w4123/GenshinVoice
> > > 数据集的下载链接[https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth，这个目前没办法注册账户并下载，请问有其他的下载数据集的方式吗？](https://obs.baimianxiao.cn/share/obs/sankagenkeshi/G_809000.pth%EF%BC%8C%E8%BF%99%E4%B8%AA%E7%9B%AE%E5%89%8D%E6%B2%A1%E5%8A%9E%E6%B3%95%E6%B3%A8%E5%86%8C%E8%B4%A6%E6%88%B7%E5%B9%B6%E4%B8%8B%E8%BD%BD%EF%BC%8C%E8%AF%B7%E9%97%AE%E6%9C%89%E5%85%B6%E4%BB%96%E7%9A%84%E4%B8%8B%E8%BD%BD%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E6%96%B9%E5%BC%8F%E5%90%97%EF%BC%9F)
> 
> 这个项目只提供原神提取的音频素材 没有数据集啊

我写这个项目的时候并不知道“数据集”指的是音频素材这些的，如果你要找.pth后缀这个文件，那他叫“模型”，你可以在百度的aistudio找到（原神多人语音）

edit：有任何问题随时reopen
